import { useEffect, useState } from "react";
import { ArrowLeft, Printer } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import Sidebar from "../components/Sidebar";
import { api } from "../api/client";
import { printCase, printLaboratoryRequest, printPrescription } from "../utils/print";

const dash = (value) => value || "—";

export default function CaseDetail() {
  const { id } = useParams(); const [record, setRecord] = useState(null); const [error, setError] = useState("");
  useEffect(() => { api(`/cases/${id}`).then(setRecord).catch((e) => setError(e.message)); }, [id]);
  if (!record) return <p className="p-8 text-slate-600">{error || "Loading case…"}</p>;
  const documentRecord = (item) => ({ ...record, ...item, patient_name: `${record.first_name} ${record.last_name}` });
  const diagnoses = record.diagnoses?.map((item) => item.diagnosis_name).join(", ");
  return <div className="flex min-h-screen bg-slate-50"><Sidebar activeItem="Consultations" /><div className="min-w-0 flex-1"><header className="m-4 rounded-3xl bg-linear-to-r from-teal-700 to-teal-500 p-6 text-white sm:m-6"><Link to={`/patients/${record.patient_id}`} className="inline-flex items-center gap-1 text-sm text-teal-100"><ArrowLeft size={16} />Patient record</Link><h1 className="mt-4 text-3xl font-bold">Consultation {record.case_number}</h1><p className="text-teal-100">{record.first_name} {record.last_name} · {record.consultation_date}</p></header><main className="space-y-6 px-4 pb-8 sm:px-6">{error && <p className="text-red-600">{error}</p>}<section className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-bold">Consultation details</h2><p className="mt-1 text-sm text-slate-500">Case status: {record.case_status}</p></div><button onClick={() => printCase(record)} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 font-semibold"><Printer size={17} />Print consultation</button></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Detail label="Chief complaint" value={record.chief_complaint} /><Detail label="History of present illness" value={record.history_present_illness} /><Detail label="Diagnosis" value={diagnoses} /><Detail label="Treatment" value={record.treatment} /><Detail label="Doctor's notes" value={record.doctor_notes} /><Detail label="Follow-up date" value={record.follow_up_date} /></div><div className="mt-5 grid gap-4 sm:grid-cols-4"><Detail label="Blood pressure" value={record.blood_pressure} /><Detail label="Temperature" value={record.temperature_c ? `${record.temperature_c} °C` : ""} /><Detail label="Weight" value={record.weight_kg ? `${record.weight_kg} kg` : ""} /><Detail label="Height" value={record.height_cm ? `${record.height_cm} cm` : ""} /></div></section><Documents title="Medicine prescriptions" rows={record.prescriptions} number="prescription_number" itemName="medicine_name" empty="No prescriptions issued for this case." onPrint={(item) => printPrescription(documentRecord(item))} /><Documents title="Laboratory requests" rows={record.laboratory_requests} number="request_number" itemName="test_name" empty="No laboratory requests issued for this case." onPrint={(item) => printLaboratoryRequest(documentRecord(item))} /></main></div></div>;
}

function Detail({ label, value }) { return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold uppercase text-slate-400">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-700">{dash(value)}</p></div>; }
function Documents({ title, rows, number, itemName, empty, onPrint }) { return <section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">{title}</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-b text-xs uppercase text-slate-400"><th className="p-3">Number</th><th className="p-3">Date</th><th className="p-3">Items</th><th /></tr></thead><tbody>{rows.length ? rows.map((item) => <tr key={item.id} className="border-b"><td className="p-3 font-semibold text-pink-600">{item[number]}</td><td className="p-3">{item.issued_date || item.requested_date}</td><td className="p-3">{item.items?.map((entry) => entry[itemName]).join(", ") || "—"}</td><td className="p-3"><button onClick={() => onPrint(item)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-sm"><Printer size={16} />Print</button></td></tr>) : <tr><td colSpan="4" className="p-6 text-center text-sm text-slate-500">{empty}</td></tr>}</tbody></table></div></section>; }
