import { useEffect, useMemo, useState } from "react";
import { CalendarDays, CreditCard, FileText, Search, ShieldCheck } from "lucide-react";
import Sidebar from "../components/Sidebar";
import { api } from "../api/client";
const config = { Appointments: { endpoint: "/appointments", icon: CalendarDays, columns: ["patient_id", "service", "appointment_date", "status"] }, "Prenatal Records": { endpoint: "/prenatal-records", icon: FileText, columns: ["patient_id", "visit_date", "gestational_age_weeks", "risk_level"] }, Billing: { endpoint: "/invoices", icon: CreditCard, columns: ["invoice_number", "patient_id", "invoice_date", "total_amount", "payment_status"] }, "Laboratory Requests": { endpoint: "/laboratory-requests", icon: FileText, columns: ["request_number", "patient_name", "requested_date", "status"] }, Settings: { endpoint: "/auth/setup-status", icon: ShieldCheck, columns: ["clinic_name", "clinic_address", "doctor_name"] } };
const label = (key) => key.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
export default function ClinicModule({ moduleName }) {
  const item = config[moduleName] || config.Settings; const [rows, setRows] = useState([]), [search, setSearch] = useState(""), [error, setError] = useState("");
  useEffect(() => { api(item.endpoint).then((data) => setRows(moduleName === "Settings" ? (data.settings ? [data.settings] : []) : data)).catch((e) => setError(e.message)); }, [item.endpoint, moduleName]);
  const filtered = useMemo(() => rows.filter((row) => JSON.stringify(row).toLowerCase().includes(search.toLowerCase())), [rows, search]); const Icon = item.icon;
  return <div className="flex min-h-screen bg-slate-50"><Sidebar activeItem={moduleName} /><div className="min-w-0 flex-1"><header className="m-4 rounded-3xl bg-linear-to-r from-pink-600 to-rose-400 p-6 text-white sm:m-6"><p className="text-sm text-pink-100">Live database records</p><h1 className="text-3xl font-bold">{moduleName}</h1></header><main className="px-4 pb-8 sm:px-6"><section className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Icon className="text-pink-600" /><div><h2 className="text-xl font-bold">Records</h2><p className="text-sm text-slate-500">{rows.length} record{rows.length === 1 ? "" : "s"} in the database</p></div></div><label className="mt-6 flex max-w-xl items-center gap-3 rounded-xl border border-slate-200 px-3 py-2.5"><Search size={18} className="text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search records" className="w-full outline-none" /></label>{error && <p className="mt-4 text-sm text-red-600">{error}</p>}<div className="mt-6 overflow-x-auto"><table className="w-full min-w-[600px] text-left"><thead><tr className="border-b text-xs uppercase text-slate-400">{item.columns.map((column) => <th key={column} className="p-3">{label(column)}</th>)}</tr></thead><tbody>{filtered.length ? filtered.map((row) => <tr key={row.id || JSON.stringify(row)} className="border-b border-slate-50">{item.columns.map((column) => <td key={column} className="p-3 text-sm">{row[column] ?? "—"}</td>)}</tr>) : <tr><td colSpan={item.columns.length} className="p-8 text-center text-sm text-slate-500">No records found.</td></tr>}</tbody></table></div></section></main></div></div>;
}
