import { useEffect, useState } from "react";
import { CalendarDays, FlaskConical, PhilippinePeso, Users } from "lucide-react";
import Sidebar from "../components/Sidebar";
import { api } from "../api/client";
const currency = new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" });
export default function Dashboard() {
  const [data, setData] = useState(null), [error, setError] = useState("");
  useEffect(() => { api("/dashboard").then(setData).catch((e) => setError(e.message)); }, []);
  const cards = data ? [["Total Patients", data.totalPatients, Users, "bg-pink-100 text-pink-600"], ["Today's Consultations", data.consultationsToday, CalendarDays, "bg-teal-100 text-teal-700"], ["Today's Income", currency.format(data.incomeToday), PhilippinePeso, "bg-emerald-100 text-emerald-700"], ["Pending Laboratory Results", data.pendingLabs, FlaskConical, "bg-amber-100 text-amber-700"]] : [];
  return <div className="flex min-h-screen bg-slate-50"><Sidebar activeItem="Dashboard" /><div className="min-w-0 flex-1"><header className="m-4 rounded-3xl bg-linear-to-r from-pink-600 to-rose-400 p-6 text-white shadow-lg sm:m-6 sm:p-8"><p className="text-sm text-pink-100">OB-GYN Clinic Management</p><h1 className="mt-1 text-3xl font-bold">Dashboard</h1><p className="mt-2 text-pink-100">Your live clinic activity at a glance.</p></header><main className="px-4 pb-8 sm:px-6">{error && <p className="mb-4 rounded-xl bg-red-50 p-3 text-red-600">{error}</p>}<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon, color]) => <div key={label} className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-slate-800">{value}</p></div><Icon className={`rounded-2xl p-2 ${color}`} size={44} /></div></div>)}</section>{!data && !error && <p className="mt-6 text-sm text-slate-500">Loading clinic data…</p>}<section className="mt-6 grid gap-6 xl:grid-cols-2"><div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Recent patients</h2><div className="mt-4 divide-y">{data?.recentPatients?.length ? data.recentPatients.map((p) => <div key={p.id} className="flex justify-between py-3"><span className="font-medium">{p.last_name}, {p.first_name}</span><span className="text-sm text-pink-600">{p.patient_number}</span></div>) : <p className="py-6 text-sm text-slate-500">No patients have been registered yet.</p>}</div></div><div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Upcoming follow-ups</h2><div className="mt-4 divide-y">{data?.followUps?.length ? data.followUps.map((f) => <div key={f.case_number} className="flex justify-between py-3"><span className="font-medium">{f.last_name}, {f.first_name}</span><span className="text-sm text-teal-700">{f.follow_up_date}</span></div>) : <p className="py-6 text-sm text-slate-500">No follow-ups are scheduled.</p>}</div></div></section></main></div></div>;
}
