import { useEffect, useMemo, useState } from "react";
import { Archive, ArrowDownToLine, ArrowUpFromLine, Boxes, Download, History, Pencil, Plus, Printer, Search, X } from "lucide-react";
import Sidebar from "../components/Sidebar";
import { api } from "../api/client";

const categories = ["Medicines","Vitamins and Supplements","Laboratory Supplies","Prenatal Supplies","Medical Equipment","Disposable Supplies","Office Supplies","Other Clinic Supplies"];
const reasons = ["Used During Consultation","Dispensed to Patient","Used for Laboratory Procedure","Used for Prenatal Checkup","Damaged","Expired","Lost","Adjustment","Other"];
const blankItem = { item_code:"",item_name:"",category:"Medicines",brand:"",description:"",unit_of_measurement:"piece",supplier:"",minimum_stock_level:"10",unit_cost:"",storage_location:"" };
const blankMove = { inventory_item_id:"",quantity:"",supplier:"",batch_number:"",expiration_date:"",unit_cost:"",reference_number:"",transaction_date:new Date().toISOString().slice(0,10),reason:"Used During Consultation",department:"",requested_by:"",remarks:"" };
const money = value => new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(Number(value||0));
const user = () => { try { return JSON.parse(localStorage.getItem("currentUser")||"{}"); } catch { return {}; } };

export default function Inventory() {
  const [tab,setTab]=useState("items"),[data,setData]=useState({items:[],summary:{}}),[history,setHistory]=useState({rows:[],pages:0,page:1}),[report,setReport]=useState({rows:[],totals:{}}),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true);
  const [historyFilter,setHistoryFilter]=useState({search:"",category:"",type:"",from:"",to:"",page:1});
  const [period,setPeriod]=useState(new Date().toISOString().slice(0,7));
  const load=async()=>{try{setLoading(true);const value=await api("/inventory/overview");setData(value)}catch(e){setNotice(e.message)}finally{setLoading(false)}};
  const loadHistory=async()=>{try{const q=new URLSearchParams(Object.entries(historyFilter).filter(([,v])=>v));setHistory(await api(`/inventory/transactions?${q}`))}catch(e){setNotice(e.message)}};
  const loadReport=async()=>{try{setReport(await api(`/inventory/reports/monthly?period=${period}`))}catch(e){setNotice(e.message)}};
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{load()},[]);
  /* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
  useEffect(()=>{if(tab==="history")loadHistory();if(tab==="reports")loadReport()},[tab,historyFilter,period]);
  /* eslint-enable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
  const show=message=>{setNotice(message);load()};
  const tabs=[["items","Inventory Items",Boxes],["stock-in","Stock In",ArrowDownToLine],["stock-out","Stock Out",ArrowUpFromLine],["history","Transaction History",History],["reports","Monthly Report",Printer]];
  return <div className="flex min-h-screen bg-slate-50"><Sidebar activeItem="Inventory"/><div className="min-w-0 flex-1">
    <header className="m-4 rounded-3xl bg-linear-to-r from-teal-700 via-emerald-600 to-cyan-500 p-6 text-white shadow-xl shadow-teal-200/50 sm:m-6"><p className="text-sm text-teal-100">Clinic supplies and medicines</p><h1 className="text-3xl font-bold">Inventory Management</h1><p className="mt-2 text-teal-50">Batch-aware stock control, expiration monitoring, and permanent movement history.</p></header>
    <main className="space-y-5 px-4 pb-10 sm:px-6">{notice&&<div className="flex justify-between rounded-2xl border border-teal-200 bg-teal-50 p-3 text-sm text-teal-800">{notice}<button onClick={()=>setNotice("")}><X size={17}/></button></div>}
      <Summary summary={data.summary}/>
      <div className="flex gap-2 overflow-x-auto rounded-2xl bg-white p-2 shadow-sm">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`flex shrink-0 items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold ${tab===id?"bg-teal-600 text-white":"text-slate-500 hover:bg-slate-50"}`}><Icon size={17}/>{label}</button>)}</div>
      {loading?<div className="h-64 animate-pulse rounded-3xl bg-white"/>:<>
        {tab==="items"&&<Items items={data.items} show={show}/>}
        {tab==="stock-in"&&<Movement mode="in" items={data.items} show={show}/>}
        {tab==="stock-out"&&<Movement mode="out" items={data.items} show={show}/>}
        {tab==="history"&&<HistoryPanel data={history} filters={historyFilter} setFilters={setHistoryFilter}/>}
        {tab==="reports"&&<Report data={report} period={period} setPeriod={setPeriod}/>}
      </>}</main></div></div>;
}

function Summary({summary={}}){const cards=[["Total Items",summary.totalItems||0,"bg-blue-50 text-blue-700"],["Low Stock",summary.lowStock||0,"bg-amber-50 text-amber-700"],["Out of Stock",summary.outOfStock||0,"bg-red-50 text-red-700"],["Near Expiry",summary.nearExpiration||0,"bg-orange-50 text-orange-700"],["Expired",summary.expired||0,"bg-rose-50 text-rose-700"],["Stock In / Month",summary.stockIn||0,"bg-emerald-50 text-emerald-700"],["Stock Out / Month",summary.stockOut||0,"bg-violet-50 text-violet-700"],["Inventory Value",money(summary.totalValue),"bg-teal-50 text-teal-700"]];return <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([l,v,c])=><div key={l} className="rounded-2xl bg-white p-4 shadow-sm"><p className="text-xs font-bold uppercase text-slate-400">{l}</p><p className={`mt-2 inline-block rounded-lg px-2 py-1 text-xl font-bold ${c}`}>{v}</p></div>)}</section>}
function Panel({title,description,children,action}){return <section className="rounded-3xl bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">{title}</h2><p className="text-sm text-slate-500">{description}</p></div>{action}</div>{children}</section>}
function Field({label,...props}){return <label className="grid gap-1.5 text-sm font-semibold text-slate-600">{label}<input {...props} className="rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>}
function Select({label,children,...props}){return <label className="grid gap-1.5 text-sm font-semibold text-slate-600">{label}<select {...props} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 font-normal">{children}</select></label>}

function Items({items,show}){const [open,setOpen]=useState(false),[edit,setEdit]=useState(null),[form,setForm]=useState(blankItem),[search,setSearch]=useState("");
 const list=useMemo(()=>items.filter(i=>`${i.item_code} ${i.item_name} ${i.category}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
 const close=()=>{setOpen(false);setEdit(null);setForm(blankItem)};const save=async e=>{e.preventDefault();try{const r=await api(edit?`/inventory/items/${edit}`:"/inventory/items",{method:edit?"PUT":"POST",body:JSON.stringify(form)});show(r.message);close()}catch(x){show(x.message)}};
 const archive=async i=>{if(!confirm(`Archive ${i.item_name}?`))return;try{const r=await api(`/inventory/items/${i.id}/archive`,{method:"PATCH",body:JSON.stringify({archived:true})});show(r.message)}catch(x){show(x.message)}};
 const set=k=>e=>setForm({...form,[k]:e.target.value});
 return <Panel title="Inventory Items" description="Add item details here; all stock changes happen through transactions." action={<button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 font-bold text-white"><Plus size={18}/>Add Item</button>}>
  {open&&<form onSubmit={save} className="mt-5 grid gap-4 rounded-2xl bg-teal-50/50 p-4 sm:grid-cols-2 lg:grid-cols-3">
   <Field label="Item Code" value={form.item_code} onChange={set("item_code")} required/><Field label="Item Name" value={form.item_name} onChange={set("item_name")} required/>
   <Select label="Category" value={form.category} onChange={set("category")}>{categories.map(c=><option key={c}>{c}</option>)}</Select>
   {["brand","description","unit_of_measurement","supplier","minimum_stock_level","unit_cost","storage_location"].map(k=><Field key={k} label={k.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())} type={["minimum_stock_level","unit_cost"].includes(k)?"number":"text"} min="0" step={k==="unit_cost"?".01":undefined} value={form[k]||""} onChange={set(k)} required={k==="unit_of_measurement"}/>)}
   <div className="flex justify-end gap-2 sm:col-span-2 lg:col-span-3"><button type="button" onClick={close} className="rounded-xl border px-4 py-2">Cancel</button><button className="rounded-xl bg-teal-600 px-5 py-2 font-bold text-white">Save Item</button></div>
  </form>}
  <div className="mt-5 flex items-center gap-2 rounded-xl border px-3 py-2 max-w-md"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search item code, name, category" className="w-full"/></div>
  <div className="mt-4 overflow-x-auto"><table className="w-full min-w-250 text-left"><thead><tr className="border-b text-xs uppercase text-slate-400">{["Code / Item","Category","Stock","Minimum","Cost","Batch / Expiry","Location","Status","Actions"].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{list.map(i=><tr key={i.id} className="border-b border-slate-100"><td className="p-3"><b>{i.item_code}</b><p>{i.item_name}</p><small className="text-slate-400">{i.brand||"No brand"}</small></td><td>{i.category}</td><td className="font-bold">{i.current_stock} {i.unit_of_measurement}</td><td>{i.minimum_stock_level}</td><td>{money(i.unit_cost)}</td><td>{i.batch_number||"—"}<small className="block text-slate-400">{i.expiration_date||"No expiry"}</small></td><td>{i.storage_location||"—"}</td><td><Status value={i.status}/></td><td><div className="flex gap-2"><button title="Edit" onClick={()=>{setEdit(i.id);setForm(i);setOpen(true)}} className="rounded-lg bg-slate-100 p-2"><Pencil size={16}/></button><button title="Archive" onClick={()=>archive(i)} className="rounded-lg bg-red-50 p-2 text-red-600"><Archive size={16}/></button></div></td></tr>)}</tbody></table></div>
 </Panel>}

function Movement({mode,items,show}){const [form,setForm]=useState(blankMove),set=k=>e=>setForm({...form,[k]:e.target.value});const selected=items.find(i=>String(i.id)===String(form.inventory_item_id));
 const save=async e=>{e.preventDefault();if(!confirm(`${mode==="in"?"Receive":"Release"} ${form.quantity} unit(s) of ${selected?.item_name}?`))return;try{const r=await api(`/inventory/stock-${mode}`,{method:"POST",body:JSON.stringify({...form,performed_by:user().fullname||user().username})});show(r.message);setForm(blankMove)}catch(x){show(x.message)}};
 return <Panel title={mode==="in"?"Receive Stock":"Release Stock"} description={mode==="in"?"Record a new batch and increase stock.":"Stock is released from the earliest-expiring eligible batch first."}><form onSubmit={save} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
  <Select label="Inventory Item" value={form.inventory_item_id} onChange={set("inventory_item_id")} required><option value="">Select item</option>{items.map(i=><option key={i.id} value={i.id}>{i.item_code} — {i.item_name} ({i.current_stock} available)</option>)}</Select>
  <Field label={mode==="in"?"Quantity Received":"Quantity Released"} type="number" min="1" max={mode==="out"?selected?.current_stock:undefined} value={form.quantity} onChange={set("quantity")} required/>
  {mode==="in"?<><Field label="Supplier" value={form.supplier} onChange={set("supplier")}/><Field label="Batch / Lot Number" value={form.batch_number} onChange={set("batch_number")}/><Field label="Expiration Date" type="date" value={form.expiration_date} onChange={set("expiration_date")}/><Field label="Unit Cost" type="number" min="0" step=".01" value={form.unit_cost} onChange={set("unit_cost")}/><Field label="Purchase Reference" value={form.reference_number} onChange={set("reference_number")}/></>:<>
   <Select label="Transaction Reason" value={form.reason} onChange={set("reason")}>{reasons.map(r=><option key={r}>{r}</option>)}</Select><Field label="Department / Clinic Area" value={form.department} onChange={set("department")}/><Field label="Requested By" value={form.requested_by} onChange={set("requested_by")}/></>}
  <Field label={mode==="in"?"Date Received":"Date Released"} type="date" value={form.transaction_date} onChange={set("transaction_date")} required/><Field label="Remarks" value={form.remarks} onChange={set("remarks")}/>
  <div className="sm:col-span-2 lg:col-span-3"><button className={`rounded-xl px-5 py-3 font-bold text-white ${mode==="in"?"bg-emerald-600":"bg-orange-600"}`}>{mode==="in"?"Confirm Stock In":"Confirm Stock Out"}</button></div>
 </form></Panel>}

function HistoryPanel({data,filters,setFilters}){const set=k=>e=>setFilters({...filters,[k]:e.target.value,page:1});return <Panel title="Transaction History" description="Permanent audit trail; corrections should be recorded as adjustments."><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Field label="Search" value={filters.search} onChange={set("search")} placeholder="Item, code, patient"/><Select label="Category" value={filters.category} onChange={set("category")}><option value="">All</option>{categories.map(c=><option key={c}>{c}</option>)}</Select><Select label="Type" value={filters.type} onChange={set("type")}><option value="">All</option>{["Stock In","Stock Out","Dispensed","Damaged","Expired","Adjustment"].map(t=><option key={t}>{t}</option>)}</Select><Field label="From" type="date" value={filters.from} onChange={set("from")}/><Field label="To" type="date" value={filters.to} onChange={set("to")}/></div>
 <div className="mt-5 overflow-x-auto"><table className="w-full min-w-250 text-left"><thead><tr className="border-b text-xs uppercase text-slate-400">{["Transaction","Item","Type","Quantity","Previous → New","Batch / Expiry","Patient / Case","Performed By","Date","Remarks"].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{data.rows?.map(t=><tr key={t.id} className="border-b border-slate-100"><td className="p-3 text-xs">{t.transaction_number}</td><td><b>{t.item_code}</b><p>{t.item_name}</p></td><td>{t.transaction_type}</td><td className="font-bold">{t.quantity}</td><td>{t.previous_stock} → {t.new_stock}</td><td>{t.batch_number||"—"}<small className="block">{t.expiration_date||""}</small></td><td>{t.patient_name||"—"}<small className="block">{t.consultation_case_id?`Case #${t.consultation_case_id}`:""}</small></td><td>{t.performed_by||"System"}</td><td>{new Date(t.transaction_date).toLocaleString()}</td><td>{t.reason||t.remarks||"—"}</td></tr>)}</tbody></table></div>
 <div className="mt-4 flex justify-end gap-2"><button disabled={data.page<=1} onClick={()=>setFilters({...filters,page:data.page-1})} className="rounded-lg border px-3 py-2 disabled:opacity-40">Previous</button><span className="px-3 py-2 text-sm">Page {data.page||1} of {data.pages||1}</span><button disabled={data.page>=data.pages} onClick={()=>setFilters({...filters,page:data.page+1})} className="rounded-lg border px-3 py-2 disabled:opacity-40">Next</button></div>
 </Panel>}

function Report({data,period,setPeriod}){const csv=()=>{const head=["Item Code","Item Name","Category","Beginning Stock","Stock In","Stock Out","Dispensed","Damaged","Expired","Ending Stock","Unit Cost","Ending Value","Status"];const lines=[head,...(data.rows||[]).map(r=>[r.item_code,r.item_name,r.category,r.beginning_stock,r.stock_in,r.stock_out,r.dispensed,r.damaged,r.expired,r.ending_stock,r.unit_cost,r.ending_value,r.status])];const blob=new Blob([lines.map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`inventory-${period}.csv`;a.click();URL.revokeObjectURL(a.href)};
 return <Panel title="Monthly Inventory Report" description="Calculated directly from permanent transaction history." action={<div className="flex gap-2"><button onClick={()=>window.print()} className="flex gap-2 rounded-xl border px-3 py-2"><Printer size={17}/>Print</button><button onClick={csv} className="flex gap-2 rounded-xl bg-teal-600 px-3 py-2 text-white"><Download size={17}/>CSV</button></div>}><Field label="Report Month" type="month" value={period} onChange={e=>setPeriod(e.target.value)}/>
 <div className="mt-4 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Items",data.totals?.items],["Stock In",data.totals?.stockIn],["Stock Out",data.totals?.stockOut],["Dispensed",data.totals?.dispensed],["Damaged / Expired",(data.totals?.damaged||0)+(data.totals?.expired||0)],["Value",money(data.totals?.value)]].map(([l,v])=><div key={l} className="rounded-xl bg-slate-50 p-3"><small className="text-slate-400">{l}</small><p className="font-bold">{v||0}</p></div>)}</div>
 <div className="mt-5 overflow-x-auto"><table className="w-full min-w-250 text-left"><thead><tr className="border-b text-xs uppercase text-slate-400">{["Code / Item","Category","Beginning","Stock In","Stock Out","Dispensed","Damaged","Expired","Ending","Unit Cost","Value","Status"].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{data.rows?.map(r=><tr key={r.id} className="border-b border-slate-100"><td className="p-3"><b>{r.item_code}</b><p>{r.item_name}</p></td><td>{r.category}</td><td>{r.beginning_stock}</td><td>{r.stock_in}</td><td>{r.stock_out}</td><td>{r.dispensed}</td><td>{r.damaged}</td><td>{r.expired}</td><td className="font-bold">{r.ending_stock}</td><td>{money(r.unit_cost)}</td><td>{money(r.ending_value)}</td><td><Status value={r.status}/></td></tr>)}</tbody></table></div>
 </Panel>}
function Status({value}){const color={Expired:"bg-red-100 text-red-700","Out of Stock":"bg-rose-100 text-rose-700","Low Stock":"bg-amber-100 text-amber-700","Near Expiration":"bg-orange-100 text-orange-700","In Stock":"bg-emerald-100 text-emerald-700"}[value]||"bg-slate-100";return <span className={`whitespace-nowrap rounded-full px-2.5 py-1 text-xs font-bold ${color}`}>{value}</span>}
