import { useMemo, useState } from "react";
import { ChevronDown, Download, Filter, MoreHorizontal, Plus, Search, Users, X } from "lucide-react";
import Sidebar from "../components/Sidebar";

const patients = [
  { id: "PT-1001", name: "Maria Santos", initials: "MS", age: 29, contact: "+63 917 123 4567", lastVisit: "Jul 10, 2026", status: "Prenatal", color: "bg-pink-100 text-pink-600" },
  { id: "PT-1002", name: "Ana Reyes", initials: "AR", age: 32, contact: "+63 918 456 7890", lastVisit: "Jul 09, 2026", status: "Follow-up", color: "bg-violet-100 text-violet-600" },
  { id: "PT-1003", name: "Liza Cruz", initials: "LC", age: 27, contact: "+63 919 234 5678", lastVisit: "Jul 08, 2026", status: "Prenatal", color: "bg-rose-100 text-rose-600" },
  { id: "PT-1004", name: "Carla Mendoza", initials: "CM", age: 35, contact: "+63 920 345 6789", lastVisit: "Jul 06, 2026", status: "Consultation", color: "bg-blue-100 text-blue-600" },
  { id: "PT-1005", name: "Joan Garcia", initials: "JG", age: 30, contact: "+63 921 567 8901", lastVisit: "Jul 05, 2026", status: "Follow-up", color: "bg-amber-100 text-amber-600" },
  { id: "PT-1006", name: "Rina Villanueva", initials: "RV", age: 26, contact: "+63 922 678 9012", lastVisit: "Jul 03, 2026", status: "Prenatal", color: "bg-fuchsia-100 text-fuchsia-600" },
];

const statusStyles = { Prenatal: "bg-pink-50 text-pink-600 ring-pink-100", "Follow-up": "bg-violet-50 text-violet-600 ring-violet-100", Consultation: "bg-blue-50 text-blue-600 ring-blue-100" };

export default function Patient() {
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("All status");
  const [showModal, setShowModal] = useState(false);
  const filteredPatients = useMemo(() => patients.filter((patient) => `${patient.name} ${patient.id} ${patient.contact}`.toLowerCase().includes(search.toLowerCase()) && (status === "All status" || patient.status === status)), [search, status]);

  return <div className="flex min-h-screen bg-slate-50"><Sidebar activeItem="Patients" /><div className="min-w-0 flex-1">
    <header className="m-4 flex flex-col gap-5 rounded-3xl bg-linear-to-r from-pink-600 to-rose-400 p-6 text-white shadow-lg sm:m-6 sm:flex-row sm:items-center sm:justify-between sm:p-8"><div><p className="mb-2 text-sm font-medium text-pink-100">Patient Management</p><h1 className="text-3xl font-bold">Patients</h1><p className="mt-2 text-pink-100">Keep patient profiles and care records organized in one place.</p></div><button onClick={() => setShowModal(true)} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-white px-5 py-3 font-semibold text-pink-600 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><Plus size={20} /> Add New Patient</button></header>
    <main className="px-4 pb-8 sm:px-6"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total Patients", "1,245", "12% from last month", "bg-pink-100 text-pink-600"],["Prenatal Care", "86", "Active patients", "bg-rose-100 text-rose-600"],["Follow-up Due", "24", "This week", "bg-violet-100 text-violet-600"],["New This Month", "48", "8% increase", "bg-blue-100 text-blue-600"]].map(([label, value, detail, classes]) => <div key={label} className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-slate-800">{value}</p></div><div className={`flex h-11 w-11 items-center justify-center rounded-2xl ${classes}`}><Users size={21} /></div></div><p className="mt-4 text-xs font-medium text-slate-400">{detail}</p></div>)}</section>
      <section className="mt-6 rounded-3xl border border-slate-100 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-xl font-bold text-slate-800">Patient Directory</h2><p className="mt-1 text-sm text-slate-500">View and manage all registered patients.</p></div><button className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-600"><Download size={17} /> Export list</button></div>
        <div className="mt-6 flex flex-col gap-3 md:flex-row"><label className="flex flex-1 items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 focus-within:border-pink-400 focus-within:bg-white"><Search size={19} className="text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by patient name, ID, or contact..." className="w-full bg-transparent text-sm text-slate-700 placeholder:text-slate-400" /></label><div className="flex gap-3"><div className="relative flex-1 md:flex-none"><Filter size={17} className="pointer-events-none absolute left-4 top-3.5 text-slate-400" /><select value={status} onChange={(event) => setStatus(event.target.value)} className="w-full appearance-none rounded-2xl border border-slate-200 bg-white py-3 pl-10 pr-10 text-sm font-medium text-slate-600 md:w-44"><option>All status</option><option>Prenatal</option><option>Follow-up</option><option>Consultation</option></select><ChevronDown size={17} className="pointer-events-none absolute right-3 top-3.5 text-slate-400" /></div><button onClick={() => { setSearch(""); setStatus("All status"); }} className="rounded-2xl border border-slate-200 px-4 text-sm font-semibold text-slate-600">Reset</button></div></div>
        <div className="mt-6 overflow-x-auto"><table className="w-full min-w-190 text-left"><thead><tr className="border-b border-slate-100 text-xs uppercase tracking-wider text-slate-400"><th className="px-3 py-4 font-semibold">Patient</th><th className="px-3 py-4 font-semibold">Patient ID</th><th className="px-3 py-4 font-semibold">Age</th><th className="px-3 py-4 font-semibold">Contact Number</th><th className="px-3 py-4 font-semibold">Last Visit</th><th className="px-3 py-4 font-semibold">Status</th><th className="px-3 py-4"></th></tr></thead><tbody>{filteredPatients.map((patient) => <tr key={patient.id} className="border-b border-slate-50 transition hover:bg-pink-50/50"><td className="px-3 py-4"><div className="flex items-center gap-3"><div className={`flex h-10 w-10 items-center justify-center rounded-full text-sm font-bold ${patient.color}`}>{patient.initials}</div><span className="font-semibold text-slate-700">{patient.name}</span></div></td><td className="px-3 py-4 text-sm font-medium text-slate-500">{patient.id}</td><td className="px-3 py-4 text-sm text-slate-600">{patient.age} years</td><td className="px-3 py-4 text-sm text-slate-600">{patient.contact}</td><td className="px-3 py-4 text-sm text-slate-600">{patient.lastVisit}</td><td className="px-3 py-4"><span className={`rounded-full px-3 py-1.5 text-xs font-semibold ring-1 ${statusStyles[patient.status]}`}>{patient.status}</span></td><td className="px-3 py-4"><button aria-label={`More options for ${patient.name}`} className="rounded-lg p-2 text-slate-400"><MoreHorizontal size={20} /></button></td></tr>)}</tbody></table></div>
        <div className="mt-5 flex flex-col gap-3 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><p>Showing <span className="font-semibold text-slate-700">{filteredPatients.length}</span> of 1,245 patients</p><div className="flex gap-2"><button className="rounded-lg border border-slate-200 px-3 py-2" disabled>Previous</button><button className="rounded-lg bg-pink-600 px-3.5 py-2 font-semibold text-white">1</button><button className="rounded-lg border border-slate-200 px-3.5 py-2">2</button><button className="rounded-lg border border-slate-200 px-3 py-2">Next</button></div></div></section></main>
  </div>{showModal && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/35 p-4"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-xl font-bold text-slate-800">Add New Patient</h2><p className="mt-1 text-sm text-slate-500">Create a profile to begin managing care.</p></div><button onClick={() => setShowModal(false)} aria-label="Close" className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={20} /></button></div><form className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium text-slate-600">First name<input className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5" placeholder="First name" /></label><label className="text-sm font-medium text-slate-600">Last name<input className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5" placeholder="Last name" /></label><label className="text-sm font-medium text-slate-600">Date of birth<input type="date" className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5" /></label><label className="text-sm font-medium text-slate-600">Contact number<input className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5" placeholder="09XX XXX XXXX" /></label><div className="sm:col-span-2 mt-2 flex justify-end gap-3"><button type="button" onClick={() => setShowModal(false)} className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-100">Cancel</button><button type="button" onClick={() => setShowModal(false)} className="rounded-xl bg-pink-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-pink-700">Save Patient</button></div></form></div></div>}</div>;
}
