import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowRight, Building2, Lock, MapPin, Stethoscope, UserRoundPlus } from "lucide-react";
import { api } from "../api/client";

export default function Register() {
  const navigate = useNavigate();
  const [form, setForm] = useState({ clinicName: "", clinicAddress: "", doctorName: "", username: "", password: "" });
  const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const update = (key) => (event) => setForm({ ...form, [key]: event.target.value });
  const submit = async (event) => { event.preventDefault(); setLoading(true); setMessage(""); try { await api("/auth/setup", { method: "POST", body: JSON.stringify(form) }); navigate("/"); } catch (error) { setMessage(error.message); } finally { setLoading(false); } };
  const fields = [["clinicName", "Clinic name", Building2, "Perdido OB-GYN Clinic"], ["clinicAddress", "Clinic address", MapPin, "Clinic address"], ["doctorName", "Doctor's name", Stethoscope, "Dr. Maria Santos"], ["username", "Administrator username", UserRoundPlus, "Choose a username"]];
  return <main className="flex min-h-screen items-center justify-center bg-linear-to-br from-rose-50 via-white to-teal-50 p-5"><form onSubmit={submit} className="w-full max-w-lg rounded-3xl border border-pink-100 bg-white p-7 shadow-xl sm:p-10"><p className="text-sm font-semibold text-teal-700">FIRST-TIME SETUP</p><h1 className="mt-2 text-3xl font-bold text-slate-800">Set up your clinic</h1><p className="mt-2 text-sm text-slate-500">This creates the only administrator account for this computer.</p><div className="mt-7 grid gap-4 sm:grid-cols-2">{fields.map(([key, label, Icon, placeholder]) => <label key={key} className={`text-sm font-semibold text-slate-600 ${key === "clinicAddress" ? "sm:col-span-2" : ""}`}>{label}<span className="relative mt-1.5 block"><Icon size={18} className="absolute left-3 top-3 text-pink-500" /><input required value={form[key]} onChange={update(key)} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-3 outline-none focus:border-pink-400" /></span></label>)}<label className="text-sm font-semibold text-slate-600 sm:col-span-2">Password<span className="relative mt-1.5 block"><Lock size={18} className="absolute left-3 top-3 text-pink-500" /><input required minLength="8" type="password" value={form.password} onChange={update("password")} placeholder="At least 8 characters" className="w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-3 outline-none focus:border-pink-400" /></span></label></div>{message && <p className="mt-4 rounded-xl bg-red-50 px-3 py-2 text-sm text-red-600">{message}</p>}<button disabled={loading} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-pink-600 py-3 font-semibold text-white disabled:opacity-60">{loading ? "Saving..." : <>Finish setup <ArrowRight size={18} /></>}</button></form></main>;
}
