import PermissionButton from "./PermissionButton";
import { useMemo, useRef, useState } from "react";
import { api } from "../api/client";
import { printStatementOfAccount } from "../utils/permissionedPrint";
const money = value => new Intl.NumberFormat("en-PH", {style:"currency",currency:"PHP"}).format(Number(value || 0));
const date = value => value ? String(value).slice(0,10) : "-";
const status = bill => bill.payment_status === "Cancelled" ? "Cancelled" : Number(bill.paid_amount)>Number(bill.total_amount) ? "Overpaid" : Number(bill.paid_amount)===Number(bill.total_amount) ? "Paid" : Number(bill.paid_amount)>0 ? "Partially Paid" : "Unpaid";
export default function BillingHistory({ rows }) {
 const [patientId,setPatientId]=useState("");
 const [search,setSearch]=useState("");
 const [detail,setDetail]=useState(null);
 const [error,setError]=useState("");
 const [loading,setLoading]=useState(false);
 const request=useRef(0);
 const patients=useMemo(()=>Array.from(new Map(rows.map(row=>[String(row.patient_id),row])).values()).sort((a,b)=>a.patient_name.localeCompare(b.patient_name)),[rows]);
 const bills=rows.filter(row=>status(row)==="Paid"&&(!patientId||String(row.patient_id)===patientId)&&`${row.invoice_number} ${row.patient_name} ${row.patient_number} ${row.case_number||""}`.toLowerCase().includes(search.toLowerCase()));
 const open=async bill=>{const token=++request.current;setDetail(null);setLoading(true);setError("");try{const result=await api(`/invoices/${bill.id}/details`);if(token===request.current)setDetail(result)}catch(err){if(token===request.current)setError(err.message)}finally{if(token===request.current)setLoading(false)}};
 return <section className="rounded-3xl bg-white p-5 shadow-sm sm:p-6">
  <h2 className="text-xl font-bold">Billing History</h2><p className="mt-1 text-sm text-slate-500">Fully paid bills, including archived patients. Open a bill to view its charges and reprint the SOA.</p>
  <div className="my-5 flex flex-wrap gap-3"><label className="grid gap-1 text-sm">Patient<select className="rounded-lg border p-2" value={patientId} onChange={event=>setPatientId(event.target.value)}><option value="">All patients</option>{patients.map(patient=><option key={patient.patient_id} value={patient.patient_id}>{patient.patient_name} ({patient.patient_number})</option>)}</select></label><label className="grid gap-1 text-sm">Search<input className="rounded-lg border p-2" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Patient, invoice, or case"/></label></div>
  <p className="mb-3 text-sm text-slate-500">{bills.length} bill(s)</p>
  <div className="max-h-[60dvh] overflow-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="sticky top-0 bg-slate-100"><tr>{["Invoice / Date","Patient","Case","Total","Paid","Balance","Status",""].map((label,index)=><th key={index} className="p-3">{label}</th>)}</tr></thead><tbody>{bills.map(bill=><tr key={bill.id} className="border-b"><td className="p-3 font-semibold">{bill.invoice_number}<span className="block text-xs font-normal">{date(bill.invoice_date)}</span></td><td>{bill.patient_name}</td><td>{bill.case_number||"Other charges"}</td><td>{money(bill.total_amount)}</td><td>{money(bill.paid_amount)}</td><td>{money(Math.max(0,Number(bill.total_amount)-Number(bill.paid_amount)))}</td><td>{status(bill)}</td><td><button onClick={()=>open(bill)} className="rounded-lg bg-pink-50 px-3 py-2 font-semibold text-pink-700">Open bill / SOA</button></td></tr>)}{!bills.length&&<tr><td colSpan={8} className="p-8 text-center">No paid bills found.</td></tr>}</tbody></table></div>
  {error&&<p role="alert" className="mt-3 text-red-600">{error}</p>}{loading&&<p className="mt-3">Loading bill...</p>}
  {detail&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" role="dialog" aria-modal="true" aria-labelledby="bill-history-title"><div className="max-h-[90dvh] w-full max-w-5xl overflow-y-auto rounded-2xl bg-white p-6"><div className="flex justify-between gap-3"><h3 id="bill-history-title" className="text-xl font-bold">Statement of Account - {detail.invoice_number}</h3><button onClick={()=>setDetail(null)}>Close</button></div><p className="my-3">{detail.patient_name} ({detail.patient_number}) | {date(detail.invoice_date)} | {status(detail)}</p>
   <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr>{["Description","Category","Quantity","Unit price","Discount","Amount"].map(label=><th key={label} className="border-b p-2">{label}</th>)}</tr></thead><tbody>{detail.items.map(item=><tr key={item.id}>{[item.description,item.category,item.quantity,money(item.unit_price),money(item.item_discount),money(item.final_amount)].map((value,index)=><td key={index} className="border-b p-2">{value}</td>)}</tr>)}</tbody></table>{!detail.items.length&&<p className="p-3">Itemized charges were not stored for this older bill. Its recorded total is preserved below.</p>}</div>
   <h4 className="mt-5 font-bold">Adjustments</h4>{detail.adjustments.length?detail.adjustments.map(item=><p key={item.id} className="mt-2 text-sm">{date(item.created_at)} - {item.adjustment_type}: {money(item.amount)} - {item.reason} {item.created_by?`(${item.created_by})`:""}</p>):<p className="text-sm text-slate-500">No adjustments.</p>}
   <div className="my-5 grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-3"><p>Total: <b>{money(detail.total_amount)}</b></p><p>Paid: <b>{money(detail.paid_amount)}</b></p><p>Balance: <b>{money(Math.max(0,Number(detail.total_amount)-Number(detail.paid_amount)))}</b></p></div>
   <h4 className="font-bold">Payment history</h4>{detail.payments.length?detail.payments.map(payment=><p key={payment.id} className="mt-2 text-sm">{date(payment.payment_date)} - {payment.receipt_number||payment.reference_number||"Payment"} - {payment.payment_method} - {money(payment.amount)} {payment.received_by?`- Received by ${payment.received_by}`:""}</p>):<p className="text-sm text-slate-500">No payment entries recorded.</p>}
   {!!detail.voided_items?.length&&<details className="mt-5"><summary>Voided charges</summary>{detail.voided_items.map(item=><p key={item.id}>{item.description} - {money(item.final_amount)} - {item.remarks}</p>)}</details>}
   <details className="mt-5"><summary>Audit history ({detail.audit?.length||0})</summary>{detail.audit?.map(entry=><details key={entry.id} className="my-2 rounded border p-2 text-xs"><summary>{entry.recorded_at} - {entry.table_name} - {entry.action}</summary><pre className="overflow-auto whitespace-pre-wrap">{JSON.stringify({before:entry.old_record?JSON.parse(entry.old_record):null,after:JSON.parse(entry.new_record)},null,2)}</pre></details>)}</details>
   <PermissionButton module="billingHistory" action="print" onClick={()=>printStatementOfAccount(detail, "billingHistory")} className="mt-6 rounded-xl bg-pink-600 px-5 py-3 font-semibold text-white">Print / Reprint SOA</PermissionButton>
  </div></div>}
 </section>;
}
