import { CheckCheck, LockKeyhole, ShieldCheck } from "lucide-react";
import { actionLabel, modules } from "../auth";
const categories = [...new Set(modules.map(module => module.category))];
const button = "rounded-xl border border-pink-200 bg-white px-3 py-2 text-sm font-semibold text-pink-700 hover:bg-pink-50 disabled:opacity-50";
export default function PermissionsEditor({ role, locked, selected, saving, onPreset, onToggle }) {
  const selectedModules = modules.filter(module => selected[module.id]?.includes("view"));
  const count = Object.values(selected).reduce((total, actions) => total + actions.length, 0);
  return <>
    <section className="rounded-2xl border border-pink-200 bg-pink-50/40 p-4 sm:p-5"><div className="flex items-center gap-3"><ShieldCheck className="text-pink-600" /><div><h3 className="text-lg font-bold">Access Permissions</h3><p className="mt-1 text-sm text-slate-600">Choose modules and actions for this user. Selecting an action also enables View.</p></div></div>
    {locked && <p className="mt-4 flex items-start gap-2 rounded-xl bg-pink-100 p-3 text-sm font-medium text-pink-900"><LockKeyhole size={18} className="shrink-0" />{role === "admin" ? "Admin always has full access. These permissions are automatically enabled and cannot be removed." : "Only Admin can change these permissions."}</p>}
    <div className="my-4 flex flex-wrap gap-2">{[["select","Select All"],["clear","Clear All"],["view","View Only"],["full","Full Access"]].map(([mode,label]) => <button key={mode} type="button" disabled={locked} onClick={() => onPreset(mode)} className={button}>{label}</button>)}</div>
    <p className="mb-5 text-xs text-slate-500">Select All enables every module; Full Access enables every action. Clear All blocks all modules. Basic patient and item lookups remain available within permitted workflows. User-management access never allows a non-admin to grant permissions.</p>
    {categories.map(category => <fieldset key={category} disabled={locked || saving} className="mb-5 last:mb-0"><legend className="mb-3 text-xs font-bold uppercase tracking-wider text-pink-800">{category}</legend><div className="grid gap-3 md:grid-cols-2">{modules.filter(module => module.category === category).map(module => <div key={module.id} className="rounded-xl border border-pink-100 bg-white p-4"><h4 className="mb-3 font-semibold text-slate-800">{module.label}</h4><div className="flex flex-wrap gap-x-5 gap-y-3">{module.actions.map(action => <label key={action} className="flex cursor-pointer items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={selected[module.id]?.includes(action) || false} onChange={event => onToggle(module.id,action,event.target.checked)} className="h-4 w-4 accent-pink-600" />{actionLabel(module.id,action)}</label>)}</div></div>)}</div></fieldset>)}
    </section>
    <section aria-live="polite" className="rounded-2xl border border-teal-200 bg-teal-50 p-5"><h3 className="flex items-center gap-2 font-bold text-teal-900"><CheckCheck size={20} />Permission summary before saving</h3><p className="mt-2 text-sm text-teal-800">{selectedModules.length} of {modules.length} modules · {count} enabled actions{role === "admin" && " · Admin access is permanent"}</p>{!selectedModules.length ? <p className="mt-3 text-sm text-amber-800">This user will be able to sign in but cannot open any module.</p> : <dl className="mt-4 grid gap-3 sm:grid-cols-2">{selectedModules.map(module => <div key={module.id}><dt className="text-sm font-semibold text-teal-950">{module.label}</dt><dd className="mt-0.5 text-xs leading-relaxed text-teal-800">{selected[module.id].map(action => actionLabel(module.id,action)).join(" · ")}</dd></div>)}</dl>}</section>
  </>;
}
