const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const Module=require('node:module');
test('other charges bill atomically, deduct unexpired inventory and save certificates',()=>{
 const filename=require.resolve('../database/database');
 const source=fs.readFileSync(filename,'utf8').replace('new Database(databasePath)','new Database(":memory:")');
 const mod=new Module(filename,module);mod.filename=filename;mod.paths=module.paths;mod._compile(source,filename);
 const db=mod.exports;const original=require.cache[filename];require.cache[filename]=mod;
 try{
  delete require.cache[require.resolve('../routes/clinic')];
  const router=require('../routes/clinic');
  const call=(method,path,body,params={},role='doctor')=>{
   const handler=router.stack.find(l=>l.route?.path===path&&l.route.methods[method]).route.stack[0].handle;
   const res={code:200,status(n){this.code=n;return this},json(b){this.body=b;return this}};
   handler({body,params,query:{},user:{role,full_name:'Test Doctor'}},res);return res;
  };
  db.exec("INSERT INTO patients (id,patient_number,first_name,last_name,birth_date) VALUES (1,'P-TEST','Test','Patient','1995-01-01')");
  const item=call('post','/inventory/items',{item_name:'Test medicine',category:'Medicines',unit_of_measurement:'piece',selling_price:25});
  assert.equal(item.code,201,JSON.stringify(item.body));
  const itemId=item.body.id;
  db.prepare('UPDATE inventory_items SET current_stock=10 WHERE id=?').run(itemId);
  db.prepare("INSERT INTO inventory_batches (inventory_item_id,quantity,expiration_date) VALUES (?,8,'2099-01-01'),(?,2,'2000-01-01')").run(itemId,itemId);
  const certId=db.prepare("SELECT id FROM charge_types WHERE name='Medical Certificate'").get().id;
  const submit=items=>call('post','/patient-charges',{patient_id:1,charge_date:'2026-09-11',items});
  const result=submit([{inventory_item_id:itemId,quantity:3,unit_amount:1},{charge_type_id:certId,quantity:1,unit_amount:100}]);
  assert.equal(result.code,201,JSON.stringify(result.body));assert.equal(result.body.total,175);
  assert.equal(new Set(result.body.charges.map(item=>item.charge_number)).size,1);
  assert.equal(db.prepare('SELECT current_stock FROM inventory_items WHERE id=?').get(itemId).current_stock,7);
  assert.equal(db.prepare('SELECT grand_total FROM invoices').get().grand_total,175);
  assert.equal(db.prepare('SELECT COUNT(*) n FROM invoices').get().n,1);
  const failed=submit([{inventory_item_id:itemId,quantity:1},{inventory_item_id:itemId,quantity:7}]);
  assert.equal(failed.code,400);assert.equal(db.prepare('SELECT current_stock FROM inventory_items WHERE id=?').get(itemId).current_stock,7);
  assert.equal(db.prepare('SELECT COUNT(*) n FROM patient_charges').get().n,2);
  assert.equal(db.prepare('SELECT COUNT(*) n FROM invoices').get().n,1);
  assert.equal(submit([{inventory_item_id:itemId,quantity:1.5}]).code,400);
  const certificate={issued_date:'2026-09-11',examination_date:'2026-09-10',purpose:'Work',findings:'Test findings\nLine two',recommendations:'Test advice',physician:'Test Doctor',license_number:'123'};
  const params={id:result.body.charges[1].id};
  assert.equal(call('put','/patient-charges/:id/certificate',certificate,params,'staff').code,403);
  assert.equal(call('put','/patient-charges/:id/certificate',{...certificate,issued_date:'2026-02-30'},params).code,400);
  assert.equal(call('put','/patient-charges/:id/certificate',certificate,{id:result.body.id}).code,400);
  assert.equal(call('put','/patient-charges/:id/certificate',certificate,params).code,200);
  const walkIn=db.prepare("SELECT id FROM patients WHERE patient_number='OPD-WALK-IN'").get();
  const walkBody={patient_id:walkIn.id,charge_type_id:certId,quantity:1,unit_amount:100,certificate:{...certificate,recipient_name:'Walk In Recipient'}};
  const walkCharge=call('post','/patient-charges',walkBody);
  assert.equal(walkCharge.code,201,JSON.stringify(walkCharge.body));
  const walkRecord=db.prepare('SELECT * FROM patient_charges WHERE id=?').get(walkCharge.body.id);
  assert.equal(walkRecord.consultation_case_id,null);
  const walkDetail=call('get','/invoices/:id/details',{}, {id:walkRecord.invoice_id});
  assert.equal(walkDetail.body.patient_name,'Walk In Recipient');
  assert.equal(walkDetail.body.case_number,'OPD Walk-in');
  const walkBill=call('get','/billings',{}).body.find(bill=>bill.id===walkRecord.invoice_id);
  assert.equal(walkBill.patient_name,'Walk In Recipient');
  assert.equal(walkBill.case_number,'OPD Walk-in');
  assert.equal(JSON.parse(walkRecord.certificate).recipient_name,'Walk In Recipient');
  assert.equal(call('post','/patient-charges',{...walkBody,certificate}).code,400);
  assert.equal(call('post','/patient-charges',{...walkBody,consultation_case_id:1}).code,400);
  const draftResult=submit([{charge_type_id:certId,quantity:1,unit_amount:100,certificate}]);
  assert.equal(draftResult.code,201,JSON.stringify(draftResult.body));
  assert.equal(JSON.parse(db.prepare('SELECT certificate FROM patient_charges WHERE id=?').get(draftResult.body.id).certificate).findings,certificate.findings);
  const before=db.prepare('SELECT COUNT(*) n FROM patient_charges').get().n;
  const badDraft=submit([{inventory_item_id:itemId,quantity:1},{charge_type_id:certId,quantity:1,unit_amount:100,certificate:{...certificate,findings:''}}]);
  assert.equal(badDraft.code,400);
  assert.equal(db.prepare('SELECT COUNT(*) n FROM patient_charges').get().n,before);
  assert.equal(db.prepare('SELECT current_stock FROM inventory_items WHERE id=?').get(itemId).current_stock,7);
  const staffDraft=call('post','/patient-charges',{patient_id:1,items:[{charge_type_id:certId,quantity:1,unit_amount:100,certificate}]},{},'staff');
  assert.equal(staffDraft.code,400);
  assert.equal(db.prepare('SELECT COUNT(*) n FROM patient_charges').get().n,before);
  const invoiceId=db.prepare('SELECT id FROM invoices WHERE invoice_number=?').get(result.body.invoice_number).id;
  const beforeView=db.prepare('SELECT * FROM invoices WHERE id=?').get(invoiceId);
  const itemsBefore=db.prepare('SELECT * FROM invoice_items WHERE invoice_id=?').all(invoiceId);
  const detail=call('get','/invoices/:id/details',{}, {id:invoiceId});
  assert.equal(detail.code,200,JSON.stringify(detail.body));
  assert.equal(detail.body.items.length,2);
  assert.deepEqual(db.prepare('SELECT * FROM invoices WHERE id=?').get(invoiceId),beforeView);
  assert.deepEqual(db.prepare('SELECT * FROM invoice_items WHERE invoice_id=?').all(invoiceId),itemsBefore);
  assert.ok(detail.body.audit.length>0);
  assert.equal(db.prepare('SELECT COUNT(*) n FROM payments WHERE invoice_id=?').get(invoiceId).n,0);
  const payment=call('post','/invoices/:id/payments',{amount:175,payment_method:'Cash'},{id:invoiceId});
  assert.equal(payment.code,201,JSON.stringify(payment.body));
  assert.match(payment.body.receipt_number,/^OR-/);
  assert.equal(db.prepare('SELECT receipt_number FROM payments WHERE invoice_id=?').get(invoiceId).receipt_number,payment.body.receipt_number);
  assert.equal(payment.body.invoice.payment_status,'Paid');

  assert.throws(()=>db.prepare('DELETE FROM invoices WHERE id=?').run(invoiceId),/permanent/);
  assert.throws(()=>db.prepare('DELETE FROM invoice_items WHERE invoice_id=?').run(invoiceId),/permanent/);
  assert.throws(()=>db.prepare('DELETE FROM billing_audit WHERE invoice_id=?').run(invoiceId),/cannot be deleted/);
  assert.equal(call('delete','/patients/:id',{}, {id:1}).code,409);
  db.prepare('UPDATE patients SET is_archived=1 WHERE id=1').run();
  assert.ok(call('get','/patients/:id/billing-history',{}, {id:1}).body.rows.length>=2);
  const rows=call('get','/patient-charges',{}).body;
  const group=rows.find(r=>r.id===result.body.id);
  assert.equal(group.items.length,2);
  assert.equal(group.total_amount,175);
  assert.equal(JSON.parse(group.items.find(r=>r.id===params.id).certificate).findings,certificate.findings);
  assert.equal(group.items[0].charge_name,'Test medicine');
  assert.equal(group.items[0].charge_number,group.items[1].charge_number);
  assert.equal(call('get','/billings',{}).body.find(b=>b.id===invoiceId).charge_numbers,result.body.charge_number);
  db.prepare('UPDATE patients SET is_archived=0 WHERE id=1').run();
  const cancelGroup=submit([{charge_type_id:certId,quantity:1,unit_amount:50},{charge_type_id:certId,quantity:2,unit_amount:25}]);
  assert.equal(cancelGroup.code,201);
  assert.notEqual(cancelGroup.body.charge_number,result.body.charge_number);
  const cancelled=call('delete','/patient-charges/:id',{reason:'Duplicate submission'},{id:cancelGroup.body.id});
  assert.equal(cancelled.code,200,JSON.stringify(cancelled.body));
  assert.equal(cancelled.body.invoice.total_amount,0);
  const cancelledRows=db.prepare('SELECT status,notes FROM patient_charges WHERE charge_number=?').all(cancelGroup.body.charge_number);
  assert.equal(cancelledRows.length,2);
  assert.ok(cancelledRows.every(item=>item.status==='Deleted'&&item.notes.includes('Duplicate submission')));
 }finally{if(original)require.cache[filename]=original;else delete require.cache[filename];db.close();}
});
